name: Init

on:
    workflow_call:

jobs:
    init_dev_ubuntu22:
        runs-on: ubuntu-22.04

        env:
            PUPPETEER_CACHE_DIR: ${{ github.workspace }}/node_modules/.chromium

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - name: Cache dev-js environment
              id: cache_dev_js_ubuntu22
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: cache_dev_js_ubuntu22_${{ hashFiles('package-lock.json') }}

            - name: Init dev-js environment
              if: steps.cache_dev_js_ubuntu22.outputs.cache-hit != 'true'
              run: |
                  npm run init-js

            - name: Cache dev-py environment
              id: cache_dev_py_ubuntu22
              uses: actions/cache@v3
              with:
                  path: .venv
                  key: cache_dev_py_ubuntu22_${{ hashFiles('pdm.lock') }}

            - name: Init dev-py environment
              if: steps.cache_dev_py_ubuntu22.outputs.cache-hit != 'true'
              run: |
                  python3.10 -m venv ".venv"
                  source .venv/bin/activate
                  pip install pdm==2.8.0
                  pdm install

            - name: Build package
              run: |
                  source .venv/bin/activate
                  npm run build

            - name: Cache package
              uses: actions/cache@v3
              with:
                  path: |
                      README.md
                      build/
                      dist/
                  key: cache_package_${{ github.run_id }}
